services:
  keycloak:
    container_name: keycloakTest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_URL=jdbc:postgresql://host.docker.internal:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=admin
      - KC_DB=postgres
    command: [
      "start-dev"
    ]
    ports:
      - '8181:8080'
    image: 'quay.io/keycloak/keycloak:latest'

